### ISSUE TITLE
No ttl on HTML

### ISSUE THREAD

**Issue by toby1kenobi** [dreamhost/varnish-vcl-collection#2]
Apologies if this is just my ignorance, I'm pretty new to Varnish. Using the Wordpress VCL I find that the ttl on HTML pages is never set (I think), so they're never cached. Other resources do get cached, just not pages - is this by design?

**Comment by getsource** [comment]
There are a couple of places that this would get set.

For general returned content (which would include html returned from WordPress, if it does not hit one of the exceptions):
https://github.com/dreamhost/varnish-vcl-collection/blob/master/wordpress-example.vcl#L105

If you include the static ruleset, you'll also get files with `.html/.htm` with an increased TTL from the default:
https://github.com/dreamhost/varnish-vcl-collection/blob/master/lib/static.vcl#L19

You'll need to make sure to include the [primary ruleset](https://github.com/dreamhost/varnish-vcl-collection/blob/master/wordpress-example.vcl) to get standard WordPress pages cached properly, if you aren't already, modified for your IP/port.

If you're doing that, take a look through the exceptions that would remove the TTL (like cookies or being logged in) to find what might be causing them to be dropped, or just directly take a look at [varnishlog](https://www.varnish-cache.org/docs/3.0/reference/varnishlog.html) to see why the page isn't being cached.

**Comment by getsource** [comment]
Closing this out for now -- feel free to comment if you find further issues with this.

**Comment by toby1kenobi** [comment]
Thanks, I'll have a look - apologies for the delay in responding, seems like I didn't get an alert after your initial response.
